#format = '$all'
format = "$all$directory$character"

[directory]
truncate_to_repo = false
truncation_length = 10
truncation_symbol = "…/"
format = "[$path]($style)"

[python]
style = 'purple'
symbol = '  '
